### ISSUE TITLE
Create unit tests for the application

### ISSUE THREAD

**Issue by dede999** [dede999/volix_validate_json_response#10]
## Description

After the request tests are made, the unit ones must follow

## Tasks (Classes to test)

1. Domanin -> Platforms
  - [x] Base (223dedc2)
  - [x] BS4 (a3000eaa)
  - [x] Selenium (78e6f458)
  - [x] Amazon (f946b609)
  - [x] Andra (b65caeb2)
  - [x] Carrefour (d0b80242)
  - [x] Magalu (2ac4c360)
  - [x] Mercado Livre (8fbe7c8e)
  - [x] Valid Test (ea0163e1)
2. Infrastructure
  - [x] Platform Factory (81b0e29b)
  - [x] Result Tracker (313f88a3)
  - [x] Setup Validation (83eeaf24)
  - [x] Validation Config (783dadab)
3. Service
  - [x] Data Validator (c24a9dfe)
4. Script de execução de testes
  - [x] unitários (2332b317)
  - [x] ponta a ponta (e2e) (5e0dfcb3)

Items 1-3: PR #14 
Item 4: PR #15
