### ISSUE TITLE
Add validation for Dimensional Platform

### ISSUE THREAD

**Issue by dede999** [dede999/volix_validate_json_response#11]
# Tasks

- [x] Implement methods for the platform validation (9815b9e5)
- [x] If necessary (as I'm wondering there will be a lot in common with Andra) create a super class to share the validation strategy (d8e8f611)
  - It was necessary, as I literally copied and pasted code from `AndraPlatform` 
- [x] Create unit tests for this platform (d8e8f611)
