### ISSUE TITLE
Support different object keys for validation tests

### ISSUE THREAD

**Issue by dede999** [dede999/volix_validate_json_response#9]
## Description

As a response to [this comment](https://github.com/Volix-PriceTech/volix-scrapings/pull/32#issuecomment-2552153128), I'm creating a solution to allow any set of keys in the validation requests

## Tasks

- [x] Create an infrastructural class to gather validation config (921bc5a3)
  - [x] Take the client and platform name to this new class (90ae7a18)
- [x] Apply this config to the validation process by adding it to the `DataValidator` (faa1f8f1)
  - there will be a `self.config` member for the instance
